---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: {{ .Values.metadata.description }}
    openshift.io/display-name: {{ .Values.metadata.displayName }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Values.metadata.namespace }}
spec: {}

