{{- if .Values.backup.enable -}}
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ .Values.metadata.namespace }}-backup
  namespace: {{ .Values.backup.veleroNamespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  schedule: {{ .Values.backup.spec.schedule | quote }}
  template:
    includedNamespaces:
    - {{ .Values.metadata.namespace }}
    snapshotVolumes: {{ .Values.backup.spec.snapshotVolumes }}
    ttl: {{ .Values.backup.spec.ttl }}
  useOwnerReferencesInBackup: false
{{- end -}}
