{{ if .Values.egressNetworkPolicy.enable -}}
---
apiVersion: network.openshift.io/v1
kind: EgressNetworkPolicy
metadata:
  name: "egress-firewall-{{ .Values.metadata.namespace }}"
  namespace: {{ .Values.metadata.namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  egress:
    {{- range .Values.egressNetworkPolicy.rules }}
  - type: Allow
    to: { {{ if eq .type "cidr" }}cidrSelector:{{ else }}dnsName:{{ end }} {{ .value }} }
    {{- end }}
  # Catch-all
  - { type: Deny, to: { cidrSelector: 0.0.0.0/0 }}
{{ end }}
